name: nations_bible
description: An app for reading the bible in multiple languages
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.1
  intl: ^0.18.1
  scrollable_positioned_list: ^0.3.8
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  generate: true

  assets:
     - assets/versions/almeida_ra.sqlite
     - assets/versions/almeida_rc.sqlite
     - assets/versions/blivre.sqlite
     - assets/versions/asv.sqlite
     - assets/versions/web.sqlite
     - assets/versions/kjv.sqlite
