part of 'language.dart';

class LanguagePortugues extends Language {
  @override
  String get languageName => 'Português';

  @override
  Map<int, LanguageBookInfo> get bookInfos => {
        1: LanguageBookInfo(languageBookName: 'Gênesis', languageBookAbbreviation: 'Gn'),
        2: LanguageBookInfo(languageBookName: 'Êxodo', languageBookAbbreviation: 'Êx'),
        3: LanguageBookInfo(languageBookName: 'Levítico', languageBookAbbreviation: 'Lv'),
        4: LanguageBookInfo(languageBookName: 'Números', languageBookAbbreviation: 'Nm'),
        5: LanguageBookInfo(languageBookName: 'Deuteronômio', languageBookAbbreviation: 'Dt'),
        6: LanguageBookInfo(languageBookName: 'Josué', languageBookAbbreviation: 'Js'),
        7: LanguageBookInfo(languageBookName: 'Juízes', languageBookAbbreviation: 'Jz'),
        8: LanguageBookInfo(languageBookName: 'Rute', languageBookAbbreviation: 'Rt'),
        9: LanguageBookInfo(languageBookName: '1 Samuel', languageBookAbbreviation: '1Sm'),
        10: LanguageBookInfo(languageBookName: '2 Samuel', languageBookAbbreviation: '2Sm'),
        11: LanguageBookInfo(languageBookName: '1 Reis', languageBookAbbreviation: '1Rs'),
        12: LanguageBookInfo(languageBookName: '2 Reis', languageBookAbbreviation: '2Rs'),
        13: LanguageBookInfo(languageBookName: '1 Crônicas', languageBookAbbreviation: '1Cr'),
        14: LanguageBookInfo(languageBookName: '2 Crônicas', languageBookAbbreviation: '2Cr'),
        15: LanguageBookInfo(languageBookName: 'Esdras', languageBookAbbreviation: 'Ed'),
        16: LanguageBookInfo(languageBookName: 'Neemias', languageBookAbbreviation: 'Ne'),
        17: LanguageBookInfo(languageBookName: 'Ester', languageBookAbbreviation: 'Et'),
        18: LanguageBookInfo(languageBookName: 'Jó', languageBookAbbreviation: 'Jó'),
        19: LanguageBookInfo(languageBookName: 'Salmos', languageBookAbbreviation: 'Sl'),
        20: LanguageBookInfo(languageBookName: 'Provérbios', languageBookAbbreviation: 'Pv'),
        21: LanguageBookInfo(languageBookName: 'Eclesiastes', languageBookAbbreviation: 'Ec'),
        22: LanguageBookInfo(languageBookName: 'Cantares', languageBookAbbreviation: 'Ct'),
        23: LanguageBookInfo(languageBookName: 'Isaías', languageBookAbbreviation: 'Is'),
        24: LanguageBookInfo(languageBookName: 'Jeremias', languageBookAbbreviation: 'Jr'),
        25: LanguageBookInfo(languageBookName: 'Lamentações', languageBookAbbreviation: 'Lm'),
        26: LanguageBookInfo(languageBookName: 'Ezequiel', languageBookAbbreviation: 'Ez'),
        27: LanguageBookInfo(languageBookName: 'Daniel', languageBookAbbreviation: 'Dn'),
        28: LanguageBookInfo(languageBookName: 'Oséias', languageBookAbbreviation: 'Os'),
        29: LanguageBookInfo(languageBookName: 'Joel', languageBookAbbreviation: 'Jl'),
        30: LanguageBookInfo(languageBookName: 'Amós', languageBookAbbreviation: 'Am'),
        31: LanguageBookInfo(languageBookName: 'Obadias', languageBookAbbreviation: 'Ob'),
        32: LanguageBookInfo(languageBookName: 'Jonas', languageBookAbbreviation: 'Jn'),
        33: LanguageBookInfo(languageBookName: 'Miquéias', languageBookAbbreviation: 'Mq'),
        34: LanguageBookInfo(languageBookName: 'Naum', languageBookAbbreviation: 'Na'),
        35: LanguageBookInfo(languageBookName: 'Habacuque', languageBookAbbreviation: 'Hc'),
        36: LanguageBookInfo(languageBookName: 'Sofonias', languageBookAbbreviation: 'Sf'),
        37: LanguageBookInfo(languageBookName: 'Ageu', languageBookAbbreviation: 'Ag'),
        38: LanguageBookInfo(languageBookName: 'Zacarias', languageBookAbbreviation: 'Zc'),
        39: LanguageBookInfo(languageBookName: 'Malaquias', languageBookAbbreviation: 'Ml'),
        40: LanguageBookInfo(languageBookName: 'Mateus', languageBookAbbreviation: 'Mt'),
        41: LanguageBookInfo(languageBookName: 'Marcos', languageBookAbbreviation: 'Mc'),
        42: LanguageBookInfo(languageBookName: 'Lucas', languageBookAbbreviation: 'Lc'),
        43: LanguageBookInfo(languageBookName: 'João', languageBookAbbreviation: 'Jo'),
        44: LanguageBookInfo(languageBookName: 'Atos dos Apóstolos', languageBookAbbreviation: 'At'),
        45: LanguageBookInfo(languageBookName: 'Romanos', languageBookAbbreviation: 'Rm'),
        46: LanguageBookInfo(languageBookName: '1 Coríntios', languageBookAbbreviation: '1Co'),
        47: LanguageBookInfo(languageBookName: '2 Coríntios', languageBookAbbreviation: '2Co'),
        48: LanguageBookInfo(languageBookName: 'Gálatas', languageBookAbbreviation: 'Gl'),
        49: LanguageBookInfo(languageBookName: 'Efésios', languageBookAbbreviation: 'Ef'),
        50: LanguageBookInfo(languageBookName: 'Filipenses', languageBookAbbreviation: 'Fp'),
        51: LanguageBookInfo(languageBookName: 'Colossenses', languageBookAbbreviation: 'Cl'),
        52: LanguageBookInfo(languageBookName: '1 Tessalonicenses', languageBookAbbreviation: '1Ts'),
        53: LanguageBookInfo(languageBookName: '2 Tessalonicenses', languageBookAbbreviation: '2Ts'),
        54: LanguageBookInfo(languageBookName: '1 Timóteo', languageBookAbbreviation: '1Tm'),
        55: LanguageBookInfo(languageBookName: '2 Timóteo', languageBookAbbreviation: '2Tm'),
        56: LanguageBookInfo(languageBookName: 'Tito', languageBookAbbreviation: 'Tt'),
        57: LanguageBookInfo(languageBookName: 'Filemom', languageBookAbbreviation: 'Fm'),
        58: LanguageBookInfo(languageBookName: 'Hebreus', languageBookAbbreviation: 'Hb'),
        59: LanguageBookInfo(languageBookName: 'Tiago', languageBookAbbreviation: 'Tg'),
        60: LanguageBookInfo(languageBookName: '1 Pedro', languageBookAbbreviation: '1Pe'),
        61: LanguageBookInfo(languageBookName: '2 Pedro', languageBookAbbreviation: '2Pe'),
        62: LanguageBookInfo(languageBookName: '1 João', languageBookAbbreviation: '1Jo'),
        63: LanguageBookInfo(languageBookName: '2 João', languageBookAbbreviation: '2Jo'),
        64: LanguageBookInfo(languageBookName: '3 João', languageBookAbbreviation: '3Jo'),
        65: LanguageBookInfo(languageBookName: 'Judas', languageBookAbbreviation: 'Jd'),
        66: LanguageBookInfo(languageBookName: 'Apocalipse', languageBookAbbreviation: 'Ap'),
      };
}
