part of 'language.dart';

class LanguageEnglish extends Language {
  @override
  String get languageLongName => 'English';

  @override
  String get languageShortName => 'EN';

  @override
  Map<int, LanguageBookInfo> get bookInfos => {
        1: LanguageBookInfo(languageBookName: 'Genesis', languageBookAbbreviation: 'Gn', languageChapterInfos: [],),
        2: LanguageBookInfo(languageBookName: 'Exodus', languageBookAbbreviation: 'Ex', languageChapterInfos: [],),
        3: LanguageBookInfo(languageBookName: 'Leviticus', languageBookAbbreviation: 'Lv', languageChapterInfos: [],),
        4: LanguageBookInfo(languageBookName: 'Numbers', languageBookAbbreviation: 'Nm', languageChapterInfos: [],),
        5: LanguageBookInfo(languageBookName: 'Deuteronomy', languageBookAbbreviation: 'Dt', languageChapterInfos: [],),
        6: LanguageBookInfo(languageBookName: 'Joshua', languageBookAbbreviation: 'Js', languageChapterInfos: [],),
        7: LanguageBookInfo(languageBookName: 'Judges', languageBookAbbreviation: 'Jg', languageChapterInfos: [],),
        8: LanguageBookInfo(languageBookName: 'Ruth', languageBookAbbreviation: 'Ru', languageChapterInfos: [],),
        9: LanguageBookInfo(languageBookName: '1 Samuel', languageBookAbbreviation: '1Sa', languageChapterInfos: [],),
        10: LanguageBookInfo(languageBookName: '2 Samuel', languageBookAbbreviation: '2Sa', languageChapterInfos: [],),
        11: LanguageBookInfo(languageBookName: '1 Kings', languageBookAbbreviation: '1Ki', languageChapterInfos: [],),
        12: LanguageBookInfo(languageBookName: '2 Kings', languageBookAbbreviation: '2Ki', languageChapterInfos: [],),
        13: LanguageBookInfo(languageBookName: '1 Chronicles', languageBookAbbreviation: '1Ch', languageChapterInfos: [],),
        14: LanguageBookInfo(languageBookName: '2 Chronicles', languageBookAbbreviation: '2Ch', languageChapterInfos: [],),
        15: LanguageBookInfo(languageBookName: 'Ezra', languageBookAbbreviation: 'Ezr', languageChapterInfos: [],),
        16: LanguageBookInfo(languageBookName: 'Nehemiah', languageBookAbbreviation: 'Ne', languageChapterInfos: [],),
        17: LanguageBookInfo(languageBookName: 'Esther', languageBookAbbreviation: 'Es', languageChapterInfos: [],),
        18: LanguageBookInfo(languageBookName: 'Job', languageBookAbbreviation: 'Job', languageChapterInfos: [],),
        19: LanguageBookInfo(languageBookName: 'Psalms', languageBookAbbreviation: 'Ps', languageChapterInfos: [],),
        20: LanguageBookInfo(languageBookName: 'Proverbs', languageBookAbbreviation: 'Pr', languageChapterInfos: [],),
        21: LanguageBookInfo(languageBookName: 'Ecclesiastes', languageBookAbbreviation: 'Ec', languageChapterInfos: [],),
        22: LanguageBookInfo(languageBookName: 'Song of Solomon', languageBookAbbreviation: 'So', languageChapterInfos: [],),
        23: LanguageBookInfo(languageBookName: 'Isaiah', languageBookAbbreviation: 'Is', languageChapterInfos: [],),
        24: LanguageBookInfo(languageBookName: 'Jeremiah', languageBookAbbreviation: 'Je', languageChapterInfos: [],),
        25: LanguageBookInfo(languageBookName: 'Lamentations', languageBookAbbreviation: 'La', languageChapterInfos: [],),
        26: LanguageBookInfo(languageBookName: 'Ezekiel', languageBookAbbreviation: 'Eze', languageChapterInfos: [],),
        27: LanguageBookInfo(languageBookName: 'Daniel', languageBookAbbreviation: 'Da', languageChapterInfos: [],),
        28: LanguageBookInfo(languageBookName: 'Hosea', languageBookAbbreviation: 'Ho', languageChapterInfos: [],),
        29: LanguageBookInfo(languageBookName: 'Joel', languageBookAbbreviation: 'Joe', languageChapterInfos: [],),
        30: LanguageBookInfo(languageBookName: 'Amos', languageBookAbbreviation: 'Am', languageChapterInfos: [],),
        31: LanguageBookInfo(languageBookName: 'Obadiah', languageBookAbbreviation: 'Ob', languageChapterInfos: [],),
        32: LanguageBookInfo(languageBookName: 'Jonah', languageBookAbbreviation: 'Jon', languageChapterInfos: [],),
        33: LanguageBookInfo(languageBookName: 'Micah', languageBookAbbreviation: 'Mic', languageChapterInfos: [],),
        34: LanguageBookInfo(languageBookName: 'Nahum', languageBookAbbreviation: 'Na', languageChapterInfos: [],),
        35: LanguageBookInfo(languageBookName: 'Habakkuk', languageBookAbbreviation: 'Hab', languageChapterInfos: [],),
        36: LanguageBookInfo(languageBookName: 'Zephaniah', languageBookAbbreviation: 'Zep', languageChapterInfos: [],),
        37: LanguageBookInfo(languageBookName: 'Haggai', languageBookAbbreviation: 'Hag', languageChapterInfos: [],),
        38: LanguageBookInfo(languageBookName: 'Zechariah', languageBookAbbreviation: 'Zec', languageChapterInfos: [],),
        39: LanguageBookInfo(languageBookName: 'Malachi', languageBookAbbreviation: 'Mal', languageChapterInfos: [],),
        40: LanguageBookInfo(languageBookName: 'Matthew', languageBookAbbreviation: 'Mt', languageChapterInfos: [],),
        41: LanguageBookInfo(languageBookName: 'Mark', languageBookAbbreviation: 'Mr', languageChapterInfos: [],),
        42: LanguageBookInfo(languageBookName: 'Luke', languageBookAbbreviation: 'Lu', languageChapterInfos: [],),
        43: LanguageBookInfo(languageBookName: 'John', languageBookAbbreviation: 'Joh', languageChapterInfos: [],),
        44: LanguageBookInfo(languageBookName: 'Acts', languageBookAbbreviation: 'Ac', languageChapterInfos: [],),
        45: LanguageBookInfo(languageBookName: 'Romans', languageBookAbbreviation: 'Ro', languageChapterInfos: [],),
        46: LanguageBookInfo(languageBookName: '1 Corinthians', languageBookAbbreviation: '1Co', languageChapterInfos: [],),
        47: LanguageBookInfo(languageBookName: '2 Corinthians', languageBookAbbreviation: '2Co', languageChapterInfos: [],),
        48: LanguageBookInfo(languageBookName: 'Galatians', languageBookAbbreviation: 'Ga', languageChapterInfos: [],),
        49: LanguageBookInfo(languageBookName: 'Ephesians', languageBookAbbreviation: 'Eph', languageChapterInfos: [],),
        50: LanguageBookInfo(languageBookName: 'Philippians', languageBookAbbreviation: 'Php', languageChapterInfos: [],),
        51: LanguageBookInfo(languageBookName: 'Colossians', languageBookAbbreviation: 'Col', languageChapterInfos: [],),
        52: LanguageBookInfo(languageBookName: '1 Thessalonians', languageBookAbbreviation: '1Th', languageChapterInfos: [],),
        53: LanguageBookInfo(languageBookName: '2 Thessalonians', languageBookAbbreviation: '2Th', languageChapterInfos: [],),
        54: LanguageBookInfo(languageBookName: '1 Timothy', languageBookAbbreviation: '1Ti', languageChapterInfos: [],),
        55: LanguageBookInfo(languageBookName: '2 Timothy', languageBookAbbreviation: '2Ti', languageChapterInfos: [],),
        56: LanguageBookInfo(languageBookName: 'Titus', languageBookAbbreviation: 'Ti', languageChapterInfos: [],),
        57: LanguageBookInfo(languageBookName: 'Philemon', languageBookAbbreviation: 'Phm', languageChapterInfos: [],),
        58: LanguageBookInfo(languageBookName: 'Hebrews', languageBookAbbreviation: 'Heb', languageChapterInfos: [],),
        59: LanguageBookInfo(languageBookName: 'James', languageBookAbbreviation: 'Jas', languageChapterInfos: [],),
        60: LanguageBookInfo(languageBookName: '1 Peter', languageBookAbbreviation: '1Pe', languageChapterInfos: [],),
        61: LanguageBookInfo(languageBookName: '2 Peter', languageBookAbbreviation: '2Pe', languageChapterInfos: [],),
        62: LanguageBookInfo(languageBookName: '1 John', languageBookAbbreviation: '1Jo', languageChapterInfos: [],),
        63: LanguageBookInfo(languageBookName: '2 John', languageBookAbbreviation: '2Jo', languageChapterInfos: [],),
        64: LanguageBookInfo(languageBookName: '3 John', languageBookAbbreviation: '3Jo', languageChapterInfos: [],),
        65: LanguageBookInfo(languageBookName: 'Jude', languageBookAbbreviation: 'Ju', languageChapterInfos: [],),
        66: LanguageBookInfo(languageBookName: 'Revelation', languageBookAbbreviation: 'Re', languageChapterInfos: [],),
      };
}
